### ISSUE TITLE
CI: run pylint, lgtm.com, codecov, pytest

### ISSUE THREAD

**Issue by robbason** [samplchallenges/SAMPL-league#12]
pylint
dependabot
lgtm

**Comment by robbason** [comment]
pylint
dependabot
lgtm

**Comment by mikemhenry** [comment]
Sweet! Any config files with those should be merged in as a PR first before PR #8

**Comment by mikemhenry** [comment]
We should mark  `app/tests/*`  as tests for LGTM

**Comment by mikemhenry** [comment]
We should also add codecov integration since we have tests
