### ISSUE TITLE
allow arbitrary key-value args to be configured at container level

### ISSUE THREAD

**Issue by robbason** [samplchallenges/SAMPL-league#75]
also must allow files, e.g. license uploads

**Comment by mikemhenry** [comment]
Should we have it where people upload a license file, keep the filename the same as they upload it, and specify that we will expose `/mnt/license/FILE_NAME` to the container?

**Comment by robbason** [comment]
we could have a 'secret' flag on these arguments, so if it's a flag that others should see it won't be secret
